ruby/blog-demo/config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'help-support', to: 'pages#helpsupport'
  resources :posts
  resources :categories

  #user 
  get 'signup', to: 'users#new' 
  resources :users, except: [:new]

  #user login & logout
  get 'signin', to: 'sessions#new' 
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'
  
end

ruby/blog-demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ruby/blog-demo/app/models/category.rb
class Category < ApplicationRecord
    
    has_many :post_categories
    has_many :posts, through: :post_categories


    validates :name, presence: true, length:{minimum: 3, maximum: 25},
    uniqueness: { case_sensitive: false }
    
    
end

ruby/blog-demo/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    has_many :post_categories
    has_many :categories, through: :post_categories
    
    has_one_attached :thumbnail
    validates :title, presence: true, length: {maximum:110, minimum:10}
    validates :content, presence: true, length: {minimum:20}
end

ruby/blog-demo/app/models/post_category.rb
class  PostCategory < ApplicationRecord
    belongs_to :post
    belongs_to :category
  end

ruby/blog-demo/app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_one_attached :profileImage
    #downcase email characters before saving to the database
    before_save {self.email = email.downcase }
    
    validates :username, presence:true, uniqueness:{ case_sensitive: false }, 
    length:{minimum: 2, maximum:30}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence:true, uniqueness:{ case_sensitive: false }, 
    format:{with: VALID_EMAIL_REGEX}
    
    has_secure_password
end

ruby/blog-demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "Please sign in to your account"
            redirect_to signin_path
        end
    end

end

ruby/blog-demo/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :find_params, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]

def index
    @categories = Category.all
         
end

def create
    @category = Category.new(category_params)
    if @category.save
        flash[:notice] =  "Category created successfully"
        redirect_to @category
    else
        render 'new'

    end
end

def new
    @category = Category.new
end

def show
    @posts = @category.posts.paginate(page: params[:page], per_page: 10) 
end

def edit
 
end

def update
 
    if @category.update(category_params)    
        flash[:notice] =  "Category updated successfully"
        redirect_to @category
    else
        render 'edit'
    end
end


def destroy
   
    @category.destroy
    flash[:notice] =  "Category deleted successfully"
    redirect_to categories_path
end

private

def find_params
    @category = Category.find(params[:id])
end

def category_params
    params.require(:category).permit(:name)
end

end

ruby/blog-demo/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index 
        @posts = Post.order("RANDOM()").paginate(page: params[:page], per_page: 10)  
    end
    def about
    end

    def helpsupport
    end

    def contact
    end
end

ruby/blog-demo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :find_params, only:[:show, :edit, :update,:destroy]
   before_action :require_user, except: [:index, :show]
   before_action :require_exact_user, only: [:edit, :update, :destroy]
   
 def index
   #  @posts = Post.all  
   @posts = Post.order(:created_at).reverse_order.paginate(page: params[:page], per_page: 10) 
 end

 def new
   @post = Post.new
 end

 def create
   @post = Post.new(post_inputs)
   @post.user = current_user
   if @post.save
      flash[:notice] = "Post created successfully"
     redirect_to @post
   else
     render 'new'
 end
end

def show
  
end

def edit
   
end

def update

   if @post.update(post_inputs)
      flash[:notice] = "Post updated successfully"
      redirect_to @post
      else
         render 'edit'
   end
end


 def destroy

   @post.destroy
   flash[:notice] = "Post deleted successfully"
   redirect_to posts_path
end


private

def find_params
   @post = Post.find(params[:id])
end

def post_inputs
   params.require(:post).permit(:title, :content, :thumbnail, category_ids:[])
end

def require_exact_user
   if current_user != @post.user
      flash[:alert] = "You do not have permission to perform this action"
         redirect_to @post
      end
end
 
end

ruby/blog-demo/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    #new session login
    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Signed in successfully"
            redirect_to user
        else
            flash.now[:alert] = "Invalid username or password"
            render 'new'
        end
    end

    #signout user
    def destroy
        session[:user_id] = nil
        flash.now[:alert] = "You signed out"
        redirect_to root_path
    end
end

ruby/blog-demo/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show,:edit,:update, :destroy]
    before_action :require_user, only: [:show]
    before_action :require_exact_user, only: [:edit,:update, :destroy]
    
#users lists
def index
    @users = User.all
end

#each user show route
def show
    @posts = @user.posts.paginate(page: params[:page], per_page: 10) 
end

#signup route or new user route
def new
    @user = User.new
end

#new user action
def create
    @user = User.new(user_params)
   
    if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Account created successfully"
        redirect_to @user
    else
      render 'new'
    end
end

#edit user route
def edit
end

#edit user action
def update
    if @user.update(user_params)
        flash[:notice] = "User updated successfully"
        redirect_to posts_path
    else
      render 'edit'
    end
end

#deletes user action
def destroy
    if @user.destroy
        flash[:notice] = "Account deleted"
        redirect_to users_path
    else
        flash[:alert] = "Unable to delete account"
    end
end



private

def user_params
    params.require(:user).permit(:username,:email, :password, :profileImage)
end

def find_user
    @user = User.find(params[:id]) 
end

def require_exact_user
    if current_user != @user
       flash[:alert] = "You do not have permission to perform this action"
          redirect_to @user
       end
 end

end

ruby/blog-demo/app/helpers/application_helper.rb
module ApplicationHelper

   
end

ruby/blog-demo/app/helpers/pages_helper.rb
module PagesHelper
end

ruby/blog-demo/app/helpers/users_helper.rb
module UsersHelper
end

ruby/blog-demo/app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category) %>

ruby/blog-demo/app/views/categories/_form.html.erb
<%= form_with(model: @category, data:{turbo:false}, local: true) do |f| %>
<div class="form_box title_box">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder:"Category name..." %>
  </div>
 

  <div class="form_box button">
  <%= f.submit(@category.new_record? ? "Create" : "Update" , class:"publish_btn") %>
</div>
  <% end %>

ruby/blog-demo/app/views/categories/edit.html.erb
<div class="new-edit">
    <h1 class="">Edit Category</h1>
    <%= render 'global/errors', obj:@category %>
    <%= render 'form'%>
    </div>

ruby/blog-demo/app/views/categories/index.html.erb
<h2 class="text-center"> Categories</h2>

<% if @categories.count > 0 %>
<div class="flex-category-boxes pt-5">
<%  @categories.each do |category| %>
<div class="category-box shadow bg-white rounded">
<P><%= link_to category.name, category_path(category) %></P>
<small><%= pluralize(category.posts.count, "post") %></small>
<div class="cat-act">

    <% if logged_in? && category.posts.any? {|post| post.user == current_user} %>
    <%= link_to "Edit", edit_category_path(category), class:"p-action edit text-success" %>
    <%= link_to "Delete", category_path(category),class:"p-action delete text-danger",
     data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
     <% end %>

</div>
</div>
<% end %>
</div>
<% else %>
    <h5 class="text-center mt-5">😒No category created yet</h5>
<% end %>

ruby/blog-demo/app/views/categories/new.html.erb
<div class="new-edit">
    <h1 class="">Add New Category</h1>
    <%= render 'global/errors', obj:@category %>
    <%= render 'form'%>
    </div>

ruby/blog-demo/app/views/categories/show.html.erb
<h2 class="mt-2 mb-3 text-center"><%= @category.name %></h2>
<% if @category.posts.count < 1 %>
    <P>No post in this category yet</P>
<% else %>
<%= render 'posts/posts' %>
<div class="apple_pagination mt-4">
    <%= will_paginate @posts, :container=> false %>
</div>
<% end %>

ruby/blog-demo/app/views/global/_errors.html.erb
<div id="errcon">
<% if obj.errors.any? %>
  <ul class="error-box">
    <h3>Oops!😒</h3>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
</div>

<script>
  setTimeout(() => {
      document.getElementById('errcon').style.display = 'none';
  }, 3000)
</script>

ruby/blog-demo/app/views/layouts/_header.html.erb
<header>
    <nav>
        <input type="checkbox" id="check">
        <label for="check" class="checkbtn">
        <i class="fa-solid fa-bars checkbtn"></i>
        </label>
        <ul>
          <li><%= link_to "Home", root_path, class:"home_link" %></li>
          <div class="nav-right">
            <% if !logged_in? %>
            <li><%= link_to "About us", about_path %></li>
            <li><%= link_to "Help & support", help_support_path %></li>
            <% end %>

            <li><%= link_to "Latests", posts_path %></li>

            <% if logged_in? %>
          <li><%= link_to "Add Posts", new_post_path %></li>
          <% end %>

          <li><%= link_to "Categories", categories_path %></li>

          <% if logged_in? %>
          <li><%= link_to "Add Category", new_category_path %></li>
          <% end %>

          <li><%= link_to "People", users_path %></li>

            <% if logged_in? %>
            <li class="signout"><%= link_to "Sign Out", signout_path,
              data:{turbo_method: :delete, turbo_confirm:"Sign out of sharp"} %></li>
              <li>@<%= link_to current_user.username, user_path(current_user) %></li>
              <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Sign In", signin_path %></li> 
          <% end %>
         
        </div>
        </ul>
      </nav>
</header>

ruby/blog-demo/app/views/layouts/_messages.html.erb
<div id="msgcon">
<% flash.each do |name, msg| %>
<div class="msgbox <%= name == 'notice' ? 'success-alert' : 'danger-alert' %>">
<%= msg %>
</div>
<% end %>
</div>

<script>
    setTimeout(() => {
        document.getElementById('msgcon').style.display = 'none';
    }, 3000)
</script>

ruby/blog-demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "posts", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "nav", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "postform", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "errors", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "postshow", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "pagination", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "about", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "category", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "message", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "signandeditform", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "users", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "profile", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
  <%= render 'layouts/header' %>
    <div class="app-con">
      <%= render 'layouts/messages' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </div>
  <footer class="footer">
    © 2023 Sharp, Inc
    </footer>
  </body>
</html>

ruby/blog-demo/app/views/posts/_form.html.erb
<%= form_with(model: @post, data:{turbo:false}, local: true) do |f| %>
<div class="form_box title_box">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder:"Your topic..." %>
  </div>
 
  <div class="form_box content_box">
    <%= f.label :content %>
    <%= f.text_area :content, placeholder:"Tell us more..." %>
  </div>

  <div class="form_box thumnail">
    <%= f.label :thumbnail %>
    <%= f.file_field :thumbnail %>
  </div>

  <div class="form_box">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.label :Category, "Pick category/categories" %><br />
      <div class="cat-opt-flex">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox-inline input_checkbox" ) {cb.check_box(class: "checkbox" ) + cb.text } %>
          <% end %>
        </div>
    </div>
  </div>


  <div class="form_box button">
  <%= f.submit(@post.new_record? ? "Publish Now" : "Update Now" , class:"publish_btn") %>
</div>
  <% end %>

ruby/blog-demo/app/views/posts/_posts.html.erb
<div class="postboxes">
    <% if @posts.count > 0 %>
    <% @posts.each do |post| %>
    <div class="postbox shadow bg-white rounded">
    <div class="post_img">
        <%= link_to post_path(post) do %>
    <% if post.thumbnail.attached? %>
    <%= image_tag(post.thumbnail )%>
    <% else %>
    <%= image_tag('nothumbnail.png') %>
    <%end%>

    <%= link_to user_path(post.user) do %>
    <div class="user_img_box">
    <% if post.user.profileImage.attached? %>
    <%= image_tag(post.user.profileImage )%>
    <% else %>
    <%= image_tag('useravatar.png') %>
    <%end%>
    </div>
    <% end %>
    </div>
    <%end%>


    <h5 class="category">
        <% if post.categories.any? %>
        <%= render post.categories %>
        <% else %>
            Uncategorized
        <% end %>
    </h5>
    
    <h3 class="title"><%= link_to truncate(post.title, length:60), post_path(post) %></h3>
    <p class="description"><%= truncate(post.content,length:100) %></p>
    
    <div class="post_buttons">
        <%= link_to "Read", post_path(post), class:"p-action read" %>
        <% if logged_in? && post.user == current_user %>
        <%= link_to "Edit", edit_post_path(post), class:"p-action edit" %>
        <%= link_to "Delete", post_path(post),class:"p-action delete",
         data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
         <% end %>

    </div>
    </div>
    <% end %>

    <% else %>
    <h3 class="text-center">😒No post created yet</h3>
    <% end %>
    </div>

ruby/blog-demo/app/views/posts/edit.html.erb
<div class="new-edit">
<h1 class="">Edit Post</h1>
<%= render 'global/errors', obj: @post %>
<%= render 'form'%>
</div>

ruby/blog-demo/app/views/posts/index.html.erb
<div class="p_s">
    <h2>Latest News</h2>
<%= render 'posts/posts' %>
<div class="apple_pagination mt-4">
    <%= will_paginate @posts, :container=> false %>
</div>
</div>

ruby/blog-demo/app/views/posts/new.html.erb
<div class="new-edit">
<h1 class="">Add New Post</h1>
<%= render 'global/errors', obj:@post %>
<%= render 'form'%>
</div>

ruby/blog-demo/app/views/posts/show.html.erb
<div class="posts_show">
    <div class="post-part">
    <h2><%= @post.title %></h2>
    </div>
    <div class="post-part">
        <div class="show-img">
    <% if @post.thumbnail.attached? %>
        <%= image_tag(@post.thumbnail, width:300) %>
    <% else %>
        <%= image_tag('nothumbnail.png', width:300) %>
     <%end%>
    </div>
     </div>
     <div class="post-part info">
        <div class="info-part">
            <div class="info-part-left">
                <div class="info-part-left-img">
                    <%= link_to user_path(@post.user) do %>
                    <% if @post.user.profileImage.attached? %>
                    <%= image_tag(@post.user.profileImage )%>
                    <% else %>
                    <%= image_tag('useravatar.png') %>
                    <% end %>
                    <%end%>
            </div>
            <b><%= @post.user.username %></b>
            </div>
            <div class="info-part-right">
                <h6>Published on <%= @post.created_at.strftime("%b %d")%></h6>
            </div>
        </div>
     </div>
     <div class="post-part content"><%= @post.content %></div>
</div>

ruby/blog-demo/app/views/users/_form.html.erb
<section class="user_form">
    <%= render '/global/errors', obj: @user %>
    <%= form_with( model: @user, data:{turbo: false}, local: true, class:"form_con") do |f| %>
    
      <div class="form_box username_box">
        <%= f.label :username %>
        <%= f.text_field :username, placeholder:"Enter username"  %>
      </div>
    
      <div class="form_box email_box">
        <%= f.label :email %>
        <%= f.email_field :email, placeholder:"Enter your Email"  %>
      </div>

      <div class="form_box password_box">
        <%= f.label :password %>
        <%= f.password_field :password, placeholder:"Enter Password"  %>
      </div>

      <div class="form_box thumnail">
        <%= f.label :picture %>
        <%= f.file_field :profileImage %>
      </div>
      
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class:"sign_btn") %>
      
    <% end %>
    </section>
    

ruby/blog-demo/app/views/users/edit.html.erb
<div class="user-form">
    <h1 class="text-center">Update Account</h1>
    <%= render 'form' %>
    </div>  

ruby/blog-demo/app/views/users/index.html.erb
<div class="all-users">
    <div class="flex-users-box">
        <% @users.each do |user| %>
        <div class="user-box">
            <div class="user-pics">
                <% if user.profileImage.attached? %>
                <%= image_tag(user.profileImage , width:300)%>
                <% else %>
                <%= image_tag('nothumbnail.png',width:300) %>
                <%end%>
                </div>
            <h5>@<%= user.username %></h5>
            <div class="profile-actions">
            <%= link_to "View profile", user_path(user) %>
                <% if logged_in? && user == current_user %>
            <%= link_to "Edit profile", edit_user_path(user) %>
            <%= link_to "Delete profile", user_path(user), 
            data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            <% end %>
        </div>
        </div>
        <br/>
        <hr/>
        <% end %>
    </div>
</div>

ruby/blog-demo/app/views/users/new.html.erb
<div class="user-form">
<h1 class="text-center">Join us Today</h1>
<%= render 'form' %>
</div>  

ruby/blog-demo/app/views/users/show.html.erb
<div class="user-profile">
    <div class="user-pics">
    <% if @user.profileImage.attached? %>
    <%= image_tag(@user.profileImage , width:300)%>
    <% else %>
    <%= image_tag('nothumbnail.png',width:300) %>
    <%end%>
    </div>
    <h3>@<%= @user.username %></h3>
    <p><%= @user.email %></p>
    <div class="profile-actions">
        <% if logged_in? && @user == current_user %>
        <%= link_to "Edit profile", edit_user_path(@user) %>
        <%= link_to "Delete profile", user_path(@user), 
        data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        <% end %>
    </div>
</div>

<div class="user-posts mt-5">
    <h3 class="text-center">Posts</h3>
<% if @user.posts.count < 1 %>
    <button class="btn btn-outline-primary">This user hasn't made any posts.</button>

<% else %>
<%= render 'posts/posts' %>
<div class="apple_pagination mt-4">
    <%= will_paginate @posts, :container=> false %>
</div>
<% end %>
</div>